window.STRINGS={
en:{
 nav:{home:'Home',story:'Our story',schedule:'Schedule',rsvp:'RSVP'},
 footer:'24 – 25 · 10 · 2026 — Phủ Lý, Ninh Bình',
 home:{eyebrow:'Together with their families',are:'are getting',married:'married',date:'Saturday 24 & Sunday 25 October 2026 · Phủ Lý, Ninh Bình',rsvp:'RSVP by 1 October',sched:'See the schedule',families:{eyebrow:'The wedding of',groom:'Lê Thanh Huy',bride:'Đỗ Trang Linh',groomSide:"Groom's family",brideSide:"Bride's family",groomParents:['Mr Lê Thanh Hùng','Mrs Nguyễn Thị Thủy'],brideParents:['Mr Đỗ Quốc Toản','Mrs Nguyễn Thị Mai'],groomAddr:'216 Route de la Brauderie, France',brideAddr:'550 Trần Hưng Đạo Street, Phủ Lý Ward, Ninh Bình'},countEyebrow:'Counting down',countTitle:'Until we say I do',units:['days','hours','minutes','seconds'],photos:['Linh and Huy in the studio','Linh and Huy with a magazine of hearts','Linh and Huy by candlelight']},
 story:{scrollHint:'Scroll',progressLabel:'Story progress',mapLabel:'Map of our journey: Paris, Seoul and Phủ Lý',places:{paris:['Paris','France'],seoul:['Seoul','Korea'],phuly:['Phủ Lý','Vietnam']},eyebrow:'How it began',script:'our',title:'Story',beats:[['2023','Met in South Korea','Linh came from Vietnam, Huy from France. We met in Seoul.'],['France · Korea','Long distance','One of us in France, the other in Korea, and a lot of video calls.'],['Together','Back in Korea','The distance ended and we were in Seoul together again.'],['Seoul','Everyday life','Shopping, cafés and a few questionable sunglasses.'],['2026','Getting married','Celebrating with our families in Phủ Lý.']]},
 sched:{eyebrow:'24 – 25 October 2026 · Phủ Lý, Ninh Bình',venueLabel:'Venue',venue:"Bride's family home",venueAddr:'550 Trần Hưng Đạo Street, Phủ Lý Ward, Ninh Bình, Vietnam',script:'the',title:'Wedding weekend',days:[{label:'Saturday · 24 October',title:'Engagement Ceremony',events:[['15:00–16:00','Bride-Receiving Ceremony','Formal Request to Take the Bride'],['16:00–18:00','Engagement Reception',"Groom's family joins the celebration"],['18:00–20:00','Family gathering & socializing','']]},{label:'Sunday · 25 October',title:'Wedding Ceremony',events:[['09:30–10:00',"Groom's family arrive",''],['10:00–11:00','Main Wedding Ceremony',''],['11:00–12:00','Wedding reception',''],['12:00–15:00','Event ends','']]}],dressEyebrow:'Dress code',dressTitle:'Wear your brightest colors',dressBody:'Áo dài warmly encouraged. Marigold, pink, red — the louder the better.',badges:['Festive','Áo dài welcome'],cta:'RSVP now'},
 rsvp:{eyebrow:'Kindly reply by 1 October',title:'Will you join us?',name:'Full name',email:'Email',attend:'Attendance',yes:'Joyfully accepts',no:'Regretfully declines',party:'Party size',partyOpts:['Just me','2 guests','3 guests','4 guests'],events:'Which events?',eventOpts:['Engagement Ceremony · Sat 24','Wedding Ceremony · Sun 25'],nameReq:'Please enter your name',sending:'Sending…',err:'Something went wrong. Please try again.',note:'A note for Linh & Huy',optional:'Optional',send:'Send RSVP',sendNo:'Send regrets',thanks:'Thank you',gotIt:'We got your RSVP',miss:'We will miss you',yesMsg:n=>(n?n.split(' ').slice(-1)[0]+', see':'See')+' you in Phủ Lý.',noMsg:'Thank you for letting us know. We will raise a glass for you.',toSched:'See the schedule',close:'Close'}
},
vi:{
 nav:{home:'Trang chủ',story:'Chuyện tình',schedule:'Lịch trình',rsvp:'Xác nhận'},
 footer:'24 – 25 · 10 · 2026 — Phủ Lý, Ninh Bình',
 home:{eyebrow:'Cùng gia đình hai bên',are:'sắp',married:'về chung một nhà',date:'Thứ bảy 24 & Chủ nhật 25 tháng 10 năm 2026 · Phủ Lý, Ninh Bình',rsvp:'Xác nhận trước 1/10',sched:'Xem lịch trình',families:{eyebrow:'Lễ thành hôn của',groom:'Lê Thanh Huy',bride:'Đỗ Trang Linh',groomSide:'Nhà Trai',brideSide:'Nhà Gái',groomParents:['Ông Lê Thanh Hùng','Bà Nguyễn Thị Thủy'],brideParents:['Ông Đỗ Quốc Toản','Bà Nguyễn Thị Mai'],groomAddr:'216 Route de la Brauderie, Pháp',brideAddr:'550 Đường Trần Hưng Đạo, P. Phủ Lý, Ninh Bình'},countEyebrow:'Đếm ngược',countTitle:'Đến ngày chung đôi',units:['ngày','giờ','phút','giây'],photos:['Linh và Huy trong studio','Linh và Huy với tạp chí trái tim','Linh và Huy dưới ánh nến']},
 story:{scrollHint:'Cuộn xuống',progressLabel:'Tiến trình câu chuyện',mapLabel:'Bản đồ hành trình của chúng mình: Paris, Seoul và Phủ Lý',places:{paris:['Paris','Pháp'],seoul:['Seoul','Hàn Quốc'],phuly:['Phủ Lý','Việt Nam']},eyebrow:'Ngày ấy bắt đầu',script:'chuyện',title:'Của chúng mình',beats:[['2023','Gặp nhau ở Hàn Quốc','Linh từ Việt Nam, Huy từ Pháp. Chúng mình gặp nhau ở Seoul.'],['Pháp · Hàn','Yêu xa','Một người ở Pháp, một người ở Hàn Quốc, và rất nhiều cuộc gọi video.'],['Bên nhau','Lại ở Hàn Quốc','Hết yêu xa, chúng mình lại ở cùng nhau tại Seoul.'],['Seoul','Cuộc sống thường ngày','Dạo phố, quán cà phê và vài cặp kính hơi kỳ quặc.'],['2026','Về chung một nhà','Tổ chức cùng gia đình hai bên ở Phủ Lý.']]},
 sched:{eyebrow:'24 – 25 tháng 10 năm 2026 · Phủ Lý, Ninh Bình',venueLabel:'Địa điểm tổ chức',venue:'Tư gia nhà gái',venueAddr:'550 Đường Trần Hưng Đạo, P. Phủ Lý, Ninh Bình, Việt Nam',script:'hai ngày',title:'Vui chung đôi',days:[{label:'Thứ bảy · 24 tháng 10',title:'Lễ Đám Hỏi',events:[['15:00–16:00','Lễ xin dâu','Nhà trai xin phép rước dâu'],['16:00–18:00','Tiệc đám hỏi','Nhà trai cùng chung vui'],['18:00–20:00','Gia đình quây quần, giao lưu','']]},{label:'Chủ nhật · 25 tháng 10',title:'Lễ Vu Quy',events:[['09:30–10:00','Nhà trai đến',''],['10:00–11:00','Lễ thành hôn',''],['11:00–12:00','Tiệc cưới',''],['12:00–15:00','Kết thúc','']]}],dressEyebrow:'Trang phục',dressTitle:'Hãy mặc thật rực rỡ',dressBody:'Rất mong được thấy mọi người diện áo dài. Vàng cúc, hồng, đỏ — càng tươi càng vui.',badges:['Rực rỡ','Chào đón áo dài'],cta:'Xác nhận ngay'},
 rsvp:{eyebrow:'Vui lòng phản hồi trước 1/10',title:'Bạn sẽ đến chung vui chứ?',name:'Họ và tên',email:'Email',attend:'Tham dự',yes:'Chắc chắn sẽ đến',no:'Rất tiếc không đến được',party:'Số người',partyOpts:['Chỉ mình tôi','2 người','3 người','4 người'],events:'Bạn tham dự phần nào?',eventOpts:['Lễ Đám Hỏi · Thứ bảy 24','Lễ Vu Quy · Chủ nhật 25'],nameReq:'Vui lòng nhập họ tên',sending:'Đang gửi…',err:'Có lỗi xảy ra. Vui lòng thử lại.',note:'Lời nhắn cho Linh & Huy',optional:'Không bắt buộc',send:'Gửi xác nhận',sendNo:'Gửi lời nhắn',thanks:'Cảm ơn',gotIt:'Đã nhận được xác nhận',miss:'Chúng mình sẽ nhớ bạn',yesMsg:n=>'Hẹn gặp '+(n?n.split(' ').slice(-1)[0]+' ':'bạn ')+'ở Phủ Lý nhé!',noMsg:'Cảm ơn bạn đã báo. Chúng mình sẽ nâng ly vì bạn.',toSched:'Xem lịch trình',close:'Đóng'}
}};
