window.STRINGS={
en:{
 nav:{home:'Home',story:'Our story',schedule:'Schedule',rsvp:'RSVP'},
 footer:'24 – 25 · 10 · 2026 — Phủ Lý, Ninh Bình',
 home:{eyebrow:'Together with their families',are:'are getting',married:'married',date:'Saturday 24 & Sunday 25 October 2026 · Phủ Lý, Ninh Bình',rsvp:'RSVP by October 18',sched:'See the schedule',families:{eyebrow:'The wedding of',groom:'Lê Thanh Huy',bride:'Đỗ Trang Linh',groomSide:"Groom's family",brideSide:"Bride's family",groomParents:['Mr Lê Thanh Hùng','Mrs Nguyễn Thị Thủy'],brideParents:['Mr Đỗ Quốc Toản','Mrs Nguyễn Thị Mai'],groomAddr:'216 Route de la Brauderie, France',brideAddr:'550 Trần Hưng Đạo Street, Phủ Lý Ward, Ninh Bình'},countEyebrow:'Counting down',countTitle:'Until we say I do',units:['days','hours','minutes','seconds'],photos:['Linh and Huy in the studio','Linh and Huy with a magazine of hearts','Linh and Huy by candlelight']},
 story:{scrollHint:'Scroll',progressLabel:'Story progress',mapLabel:'Map of our journey: Paris, Seoul and Phủ Lý',places:{paris:['Paris','France'],seoul:['Seoul','Korea'],phuly:['Phủ Lý','Vietnam']},eyebrow:'How it began',script:'our',title:'Story',beats:[['We Met in Seoul','Linh came from Vietnam and Huy from France, both to South Korea to study. In the heart of Seoul, they happened to meet — and from an ordinary coffee date, their story began.'],['Miles Apart','Huy returned to France while Linh stayed in South Korea for work. Between them were more than 8,900 km and an eight-hour time difference. Yet the distance only made every reunion even more worth looking forward to.'],['Back to Seoul','Huy returned to Seoul for work, and their long-distance days finally came to an end. Calls were replaced by dates, trips, and everyday moments together. After such a long journey, they were finally in the same city again.'],['Our Next Stop','From Seoul, their story will continue to a new destination. In 2026, Linh and Huy decided to build a home together, officially becoming a family and beginning a new chapter of their lives.']]},
 sched:{eyebrow:'24 – 25 October 2026 · Phủ Lý, Ninh Bình',venueLabel:'Venue',venue:"Bride's family home",venueAddr:'550 Trần Hưng Đạo Street, Phủ Lý Ward, Ninh Bình, Vietnam',script:'the',title:'Wedding weekend',days:[{label:'Saturday · 24 October',title:'Engagement Ceremony',events:[['14:30','Guest Arrival',''],['15:00','Engagement Ceremony',''],['16:30','Reception','']]},{label:'Sunday · 25 October',title:'Wedding Ceremony',events:[['09:00','Guest Arrival',''],['10:00','Bride’s Wedding Ceremony',''],['10:40','Reception','']]}],dressEyebrow:'Dress code',dressTitle:'Wear your brightest colors',dressBody:'Áo dài warmly encouraged. Marigold, pink, red — the louder the better.',badges:['Festive','Áo dài welcome'],cta:'RSVP now'},
 rsvp:{eyebrow:'Kindly reply by October 18',title:'Will you join us?',name:'Full name',email:'Email',attend:'Attendance',yes:'Joyfully accepts',no:'Regretfully declines',party:'Party size',partyOpts:['Just me','2 guests','3 guests','4 guests'],events:'Which events?',eventOpts:['Engagement Ceremony · Sat 24','Wedding Ceremony · Sun 25'],nameReq:'Please enter your name',sending:'Sending…',err:'Something went wrong. Please try again.',note:'A note for Linh & Huy',optional:'Optional',send:'Send RSVP',sendNo:'Send regrets',thanks:'Thank you',gotIt:'We got your RSVP',miss:'We will miss you',yesMsg:n=>(n?n.split(' ').slice(-1)[0]+', see':'See')+' you in Phủ Lý.',noMsg:'Thank you for letting us know. We will raise a glass for you.',toSched:'See the schedule',close:'Close'}
},
vi:{
 nav:{home:'Trang chủ',story:'Chuyện tình',schedule:'Lịch trình',rsvp:'Xác nhận'},
 footer:'24 – 25 · 10 · 2026 — Phủ Lý, Ninh Bình',
 home:{eyebrow:'Cùng gia đình hai bên',are:'sắp',married:'về chung một nhà',date:'Thứ bảy 24 & Chủ nhật 25 tháng 10 năm 2026 · Phủ Lý, Ninh Bình',rsvp:'Xác nhận trước 18/10',sched:'Xem lịch trình',families:{eyebrow:'Lễ thành hôn của',groom:'Lê Thanh Huy',bride:'Đỗ Trang Linh',groomSide:'Nhà Trai',brideSide:'Nhà Gái',groomParents:['Ông Lê Thanh Hùng','Bà Nguyễn Thị Thủy'],brideParents:['Ông Đỗ Quốc Toản','Bà Nguyễn Thị Mai'],groomAddr:'216 Route de la Brauderie, Pháp',brideAddr:'550 Đường Trần Hưng Đạo, P. Phủ Lý, Ninh Bình'},countEyebrow:'Đếm ngược',countTitle:'Đến ngày chung đôi',units:['ngày','giờ','phút','giây'],photos:['Linh và Huy trong studio','Linh và Huy với tạp chí trái tim','Linh và Huy dưới ánh nến']},
 story:{scrollHint:'Cuộn xuống',progressLabel:'Tiến trình câu chuyện',mapLabel:'Bản đồ hành trình của chúng mình: Paris, Seoul và Phủ Lý',places:{paris:['Paris','Pháp'],seoul:['Seoul','Hàn Quốc'],phuly:['Phủ Lý','Việt Nam']},eyebrow:'Ngày ấy bắt đầu',script:'chuyện',title:'Của chúng mình',beats:[['Gặp nhau ở Seoul','Linh từ Việt Nam và Huy từ Pháp cùng đến Hàn Quốc học tập. Giữa lòng Seoul, hai người tình cờ gặp nhau — và từ một cuộc hẹn cà phê rất đỗi bình thường, câu chuyện của chúng mình bắt đầu.'],['Cách nhau nghìn dặm','Huy trở về Pháp, còn Linh ở lại Hàn Quốc làm việc. Giữa chúng mình là khoảng cách hơn 8.900 km và 8 tiếng lệch múi giờ. Nhưng khoảng cách chỉ khiến những lần gặp lại càng trở nên đáng mong chờ hơn.'],['Trở lại Seoul','Huy trở lại Seoul làm việc, và những ngày yêu xa cuối cùng cũng khép lại. Những cuộc gọi được thay bằng những buổi hẹn, những chuyến đi và những khoảnh khắc đời thường. Sau một vòng rất dài, chúng mình lại được ở cùng một thành phố.'],['Điểm đến tiếp theo','Từ Seoul, câu chuyện của chúng mình sẽ tiếp tục đến một điểm đến mới. Linh và Huy quyết định về chung một nhà, chính thức trở thành gia đình của nhau và bắt đầu chương mới trong cuộc đời.']]},
 sched:{eyebrow:'24 – 25 tháng 10 năm 2026 · Phủ Lý, Ninh Bình',venueLabel:'Địa điểm tổ chức',venue:'Tư gia nhà gái',venueAddr:'550 Đường Trần Hưng Đạo, P. Phủ Lý, Ninh Bình, Việt Nam',script:'hai ngày',title:'Vui chung đôi',days:[{label:'Thứ bảy · 24 tháng 10',title:'Lễ Đám Hỏi',events:[['14:30','Đón khách',''],['15:00','Lễ đám hỏi',''],['16:30','Tiệc đám hỏi','']]},{label:'Chủ nhật · 25 tháng 10',title:'Lễ Vu Quy',events:[['09:00','Đón khách',''],['10:00','Lễ Vu Quy',''],['10:40','Tiệc cưới','']]}],dressEyebrow:'Trang phục',dressTitle:'Hãy mặc thật rực rỡ',dressBody:'Rất mong được thấy mọi người diện áo dài. Vàng cúc, hồng, đỏ — càng tươi càng vui.',badges:['Rực rỡ','Chào đón áo dài'],cta:'Xác nhận ngay'},
 rsvp:{eyebrow:'Vui lòng phản hồi trước 18/10',title:'Bạn sẽ đến chung vui chứ?',name:'Họ và tên',email:'Email',attend:'Tham dự',yes:'Chắc chắn sẽ đến',no:'Rất tiếc không đến được',party:'Số người',partyOpts:['Chỉ mình tôi','2 người','3 người','4 người'],events:'Bạn tham dự phần nào?',eventOpts:['Lễ Đám Hỏi · Thứ bảy 24','Lễ Vu Quy · Chủ nhật 25'],nameReq:'Vui lòng nhập họ tên',sending:'Đang gửi…',err:'Có lỗi xảy ra. Vui lòng thử lại.',note:'Lời nhắn cho Linh & Huy',optional:'Không bắt buộc',send:'Gửi xác nhận',sendNo:'Gửi lời nhắn',thanks:'Cảm ơn',gotIt:'Đã nhận được xác nhận',miss:'Chúng mình sẽ nhớ bạn',yesMsg:n=>'Hẹn gặp '+(n?n.split(' ').slice(-1)[0]+' ':'bạn ')+'ở Phủ Lý nhé!',noMsg:'Cảm ơn bạn đã báo. Chúng mình sẽ nâng ly vì bạn.',toSched:'Xem lịch trình',close:'Đóng'}
}};
